### ISSUE TITLE
Analising the data experiments

### ISSUE THREAD

**Issue by UelisonSantos** [stanford-futuredata/InQuest#4]
Hi,

Thank you for your help in the code corrections! I was able to run the code and get the results.

In the experiments, we have 6 video datasets, but what is available here in the code is the proxy scores from the TASTI embeddings, did I get right? 
Is there any code providing the scores for the videos and the videos itself?

**Comment by mdr223** [comment]
Hi there,

Sorry for the delayed response, and I'm glad you were able to get the results!

As for the proxy scores, you are correct that they are from the TASTI embeddings. I think that Daniel Kang might still have access to the source videos; the source code for TASTI is open sourced I believe: https://github.com/stanford-futuredata/tasti/blob/master/README.md

If you want to use those specific videos I would suggest either reaching out to Daniel, or possibly following the chain of research papers he published because one of the earlier ones might have a link to a public repository with them (I can't recall off the top of my head though).
